import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const URL='https://eb69c8de-c627-47d4-b0bd-246d961cbfd3.mock.pstmn.io/youtube?class=10th&subject=Maths'

export async function getServerSideProps(){
  const res=await fetch(URL);
  const data=await res.json();
  return{
    props:{
      data

    }
  }
}
// const url ="https://www.youtube.com/watch?v=QWG2L7KF0ZA"

function getId(url) {
  // const regExp = /^.(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]).*/;
  // const match = url.match(regExp);
  // console.log(match,"ttttttttttt");
  var res = url.split('=')[1];
  console.log(res, ' OOOOOOOOOOOOOOOOOOOOOOOooooooooooo');
  return res;
  //  (match && match[2].length === 11)
  //   ?
     match[2]
   
    // : null;
}
  



export default function Home({data}) {
 
// console.log('Video ID drrrrrrrrrrrrrrrr:', videoId,  iframeMarkup)
  console.log("data",data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
          My PlayList
        </h1>

        <p className={styles.description}>
          Get started by editing{''}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul className={styles.grid}>
          {
            data.map((item)=>{


               const videoId = getId(item['link']);
  
  const iframeMarkup = '<iframe width="250" height="315" src="//www.youtube.com/embed/' 
    + videoId + ' frameborder="0" allowfullscreen></iframe>';

    

              console.log(item,"item");
              const {id,snippet}=item;
              // const {title}=snippet
              return(<li  className={styles.card}>
                <a href="">
                  <h2>{item.title}</h2>
                  <h2> {item.description}</h2>
                  {/* <img src={item.link}/> */}
                  {/* <video src='https://youtu.be/h1hdxIV-03M'/> */}
                  <div dangerouslySetInnerHTML={{ __html: iframeMarkup }}></div>
                  {/* <p>Find in-depth information about Next.js features and API.</p> */}
                </a>
                </li>)
            })
          }
          
</ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
